INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1, 8795, 'Ice');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (2, 7891, 'Candy');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (3, 1054, 'Beer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (4, 8972, 'Tomato - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (5, 546, 'Tomato');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (6, 1564, 'Gum');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (7, 9315, 'Wine - Cabernet Sauvignon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (8, 5433, 'Pike - Frozen Fillet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (9, 899, 'Nantucket Pine Orangebanana');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (10, 9579, 'Beans - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (11, 2039, 'Doilies - 10, Paper');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (12, 6680, 'Garbage Bags - Clear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (13, 9950, 'Container - Clear 32 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (14, 9216, 'Cookie Double Choco');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (15, 3593, 'Appetizer - Southwestern');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (16, 4110, 'Spinach - Spinach Leaf');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (17, 7331, 'Pork - Belly Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (18, 4282, 'Beef - Ground Medium');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (19, 635, 'Steampan - Foil');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (20, 608, 'Pepper - Scotch Bonnet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (21, 32, 'Jello - Assorted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (22, 237, 'Sugar - Brown');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (23, 3188, 'Shrimp - Black Tiger 16/20');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (24, 7509, 'Wine - Cotes Du Rhone Parallele');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (25, 9356, 'Bread - Frozen Basket Variety');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (26, 3009, 'Shrimp - Baby, Cold Water');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (27, 3584, 'Olives - Morracan Dired');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (28, 7010, 'Wine - Stoneliegh Sauvignon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (29, 2849, 'Pate - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (30, 390, 'Cookie - Dough Variety');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (31, 9599, 'Veal - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (32, 4394, 'Pepper - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (33, 6063, 'Cabbage - Savoy');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (34, 6628, 'Appetizer - Crab And Brie');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (35, 6134, 'Wine - Puligny Montrachet A.');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (36, 9018, 'Beans - Black Bean, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (37, 8665, 'Sauce - Cranberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (38, 5805, 'Wine - Domaine Boyar Royal');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (39, 9827, 'Saskatoon Berries - Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (40, 1830, 'Scotch - Queen Anne');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (41, 9267, 'Coffee - Decaffeinato Coffee');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (42, 7813, 'Knife Plastic - White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (43, 3637, 'Drambuie');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (44, 5573, 'Muffin - Mix - Creme Brule 15l');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (45, 6098, 'V8 - Vegetable Cocktail');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (46, 7942, 'Food Colouring - Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (47, 7028, 'Potatoes - Peeled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (48, 388, 'Muffin Mix - Corn Harvest');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (49, 2222, 'Wine - Pinot Noir Stoneleigh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (50, 7430, 'Dr. Pepper - 355ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (51, 2370, 'Iced Tea - Lemon, 460 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (52, 2307, 'Oil - Shortening - All - Purpose');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (53, 200, 'Tart Shells - Savory, 3');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (54, 7894, 'Chip - Potato Dill Pickle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (55, 949, 'Lemon Tarts');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (56, 1117, 'Olive - Spread Tapenade');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (57, 25, 'Crab - Soft Shell');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (58, 2562, 'Onions - Dried, Chopped');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (59, 8996, 'Cheese - Pont Couvert');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (60, 3470, 'Sausage - Breakfast');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (61, 2668, 'Flower - Commercial Bronze');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (62, 9842, 'Cinnamon Buns Sticky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (63, 8957, 'Monkfish - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (64, 5549, 'Capon - Breast, Wing On');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (65, 8013, 'Cheese - Cambozola');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (66, 1631, 'Bread - Crumbs, Bulk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (67, 8012, 'Sage Derby');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (68, 9522, 'Peach - Halves');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (69, 5742, 'Yogurt - Peach, 175 Gr');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (70, 9249, 'Wine - Red, Colio Cabernet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (71, 1132, 'Pork - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (72, 2632, 'Piping - Bags Quizna');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (73, 830, 'Chicken Thigh - Bone Out');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (74, 249, 'Pork - Backfat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (75, 4066, 'Zucchini - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (76, 3078, 'Wheat - Soft Kernal Of Wheat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (77, 1530, 'Hickory Smoke, Liquid');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (78, 5751, 'Container - Foam Dixie 12 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (79, 5875, 'Pepper - Roasted Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (80, 11, 'Appetizer - Tarragon Chicken');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (81, 763, 'Magnotta Bel Paese Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (82, 307, 'Appetizer - Asian Shrimp Roll');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (83, 3986, 'Beef - Top Sirloin - Aaa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (84, 8017, 'Chocolate - Sugar Free Semi Choc');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (85, 8866, 'Wine - Sogrape Mateus Rose');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (86, 9088, 'Toamtoes 6x7 Select');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (87, 7208, 'Wiberg Cure');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (88, 6151, 'Nut - Pecan, Pieces');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (89, 4842, 'Sauce - Plum');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (90, 5020, 'Vinegar - Tarragon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (91, 2770, 'Lobster - Tail 6 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (92, 7458, 'Wine - Fume Blanc Fetzer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (93, 6177, 'Soup - Beef, Base Mix');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (94, 7122, 'Sponge Cake Mix - Chocolate');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (95, 2983, 'Wakami Seaweed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (96, 9807, 'Egg Patty Fried');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (97, 3519, 'Pork - Sausage Casing');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (98, 5851, 'Cape Capensis - Fillet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (99, 6477, 'Eggplant - Baby');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (100, 4442, 'Soup - Beef Conomme, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (101, 2267, 'Beer - Moosehead');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (102, 308, 'Cheese - Sheep Milk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (103, 3652, 'Fish - Bones');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (104, 7417, 'Gingerale - Diet - Schweppes');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (105, 4281, 'Soup - French Can Pea');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (106, 8984, 'Versatainer Nc - 888');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (107, 5968, 'Lychee - Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (108, 137, 'Orange - Tangerine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (109, 9907, 'Bananas');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (110, 2077, 'Oil - Safflower');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (111, 1573, 'Rootbeer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (112, 3641, 'Beef - Kobe Striploin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (113, 4497, 'Trout - Rainbow, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (114, 6333, 'Rambutan');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (115, 1169, 'Shrimp - Baby, Cold Water');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (116, 7944, 'Chocolate - Semi Sweet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (117, 7714, 'Schnappes - Peach, Walkers');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (118, 3830, 'Cheese - Brick With Onion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (119, 3909, 'Icecream Bar - Del Monte');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (120, 5659, 'Beef - Ground, Extra Lean, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (121, 7825, 'Irish Cream - Baileys');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (122, 2340, 'Pumpkin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (123, 2683, 'Soupfoamcont12oz 112con');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (124, 4295, 'Muffin Puck Ww Carrot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (125, 6336, 'Wine - White, Colubia Cresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (126, 1340, 'Ketchup - Tomato');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (127, 173, 'Oil - Truffle, White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (128, 5251, 'Soup - Campbells Pasta Fagioli');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (129, 5200, 'Tomatoes - Orange');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (130, 7635, 'Tart Shells - Savory, 2');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (131, 77, 'Wine - Niagara,vqa Reisling');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (132, 2185, 'Beef - Top Sirloin - Aaa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (133, 8358, 'Quail - Jumbo Boneless');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (134, 1512, 'Taro Leaves');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (135, 532, 'Juice - V8 Splash');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (136, 5243, 'Wine - Chateauneuf Du Pape');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (137, 8340, 'Wine - Marlbourough Sauv Blanc');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (138, 8601, 'Skewers - Bamboo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (139, 4977, 'Pepper - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (140, 7577, 'Nutmeg - Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (141, 6466, 'Soup Campbells Split Pea And Ham');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (142, 8464, 'Bagelers');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (143, 4954, 'Tea - Decaf 1 Cup');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (144, 4470, 'Tomatoes - Diced, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (145, 3615, 'Oneshot Automatic Soap System');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (146, 9900, 'Fireball Whisky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (147, 4005, 'Taro Root');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (148, 3909, 'Anisette - Mcguiness');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (149, 3966, 'Longos - Chicken Curried');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (150, 2905, 'Coke - Classic, 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (151, 1851, 'Swordfish Loin Portions');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (152, 9905, 'Sugar - Palm');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (153, 7687, 'Wine - Cotes Du Rhone Parallele');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (154, 2192, 'Sauce - Demi Glace');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (155, 5068, 'Garbag Bags - Black');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (156, 6890, 'Tarts Assorted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (157, 180, 'Broom - Corn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (158, 4488, 'Sage - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (159, 8453, 'Rice Paper');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (160, 7113, 'Cleaner - Bleach');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (161, 6638, 'Filling - Mince Meat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (162, 2683, 'Turkey - Oven Roast Breast');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (163, 2453, 'Gingerale - Diet - Schweppes');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (164, 3570, 'Soda Water - Club Soda, 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (165, 5205, 'Appetizer - Smoked Salmon / Dill');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (166, 5702, 'Lid Coffee Cup 8oz Blk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (167, 6272, 'Lobster - Base');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (168, 4644, 'Quail - Whole, Boneless');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (169, 7893, 'Black Currants');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (170, 3368, 'Red Currants');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (171, 6586, 'Halibut - Steaks');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (172, 4948, 'Soup - Campbells Beef Noodle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (173, 4347, 'Sauce - Caesar Dressing');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (174, 4149, 'Pepper - Cayenne');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (175, 2119, 'Rice Pilaf, Dry,package');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (176, 2091, 'Squash - Butternut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (177, 1980, 'Parasol Pick Stir Stick');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (178, 4051, 'Pate - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (179, 1605, 'Saskatoon Berries - Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (180, 1629, 'Sauce - Sesame Thai Dressing');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (181, 7167, 'Coffee - Ristretto Coffee Capsule');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (182, 1793, 'Wine - German Riesling');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (183, 5551, 'Mushroom - Morels, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (184, 1869, 'Allspice - Jamaican');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (185, 2774, 'Wine - Delicato Merlot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (186, 2598, 'Aspic - Light');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (187, 109, 'Vaccum Bag - 14x20');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (188, 1423, 'Veal - Knuckle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (189, 1519, 'Ham Black Forest');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (190, 3438, 'Olive - Spread Tapenade');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (191, 9322, 'Thyme - Dried');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (192, 5654, 'Cheese Cloth No 60');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (193, 7172, 'Cornflakes');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (194, 6648, 'Cherries - Bing, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (195, 9728, 'Pepper - Cayenne');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (196, 202, 'Island Oasis - Mango Daiquiri');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (197, 9144, 'Turkey - Breast, Double');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (198, 8736, 'Icecream - Dstk Super Cone');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (199, 3017, 'Lobster - Live');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (200, 6055, 'Pail For Lid 1537');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (201, 6935, 'Durian Fruit');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (202, 2254, 'Beef - Striploin Aa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (203, 6178, 'Bok Choy - Baby');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (204, 4925, 'Sauce - Mint');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (205, 7164, 'Paste - Black Olive');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (206, 4841, 'Soup Campbells Split Pea And Ham');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (207, 8609, 'Scallops - In Shell');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (208, 2433, 'Turnip - White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (209, 530, 'Teriyaki Sauce');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (210, 5598, 'Smoked Tongue');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (211, 8349, 'Basil - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (212, 5755, 'Juice - Apple, 341 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (213, 3408, 'Cheese - La Sauvagine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (214, 1473, 'Carrots - Mini, Stem On');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (215, 2783, 'Turkey - Breast, Bone - In');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (216, 6665, 'Coke - Diet, 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (217, 6869, 'Blue Curacao - Marie Brizard');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (218, 6423, 'Juice - Lagoon Mango');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (219, 8632, 'Appetizer - Tarragon Chicken');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (220, 3228, 'Horseradish Root');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (221, 4409, 'Veal - Round, Eye Of');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (222, 3035, 'Bandage - Finger Cots');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (223, 8737, 'Wine - Cotes Du Rhone');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (224, 4587, 'Wine - White, Colubia Cresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (225, 1525, 'Puree - Pear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (226, 2853, 'Tuna - Yellowfin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (227, 3592, 'Quail - Eggs, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (228, 3550, 'Crush - Orange, 355ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (229, 8563, 'Prunes - Pitted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (230, 225, 'Beef - Ground Lean Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (231, 9837, 'Pate - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (232, 374, 'Salt - Rock, Course');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (233, 4000, 'Onions - Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (234, 9723, 'Pork - Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (235, 1311, 'French Kiss Vanilla');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (236, 9775, 'Zucchini - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (237, 994, 'Cheese - Perron Cheddar');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (238, 5940, 'Snapple Raspberry Tea');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (239, 2547, 'Cilantro / Coriander - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (240, 302, 'Bay Leaf Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (241, 8896, 'Beef Ground Medium');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (242, 5021, 'Sour Puss Raspberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (243, 2390, 'Bread Cranberry Foccacia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (244, 3119, 'Lamb - Shanks');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (245, 1280, 'Ham - Virginia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (246, 8681, 'Red Snapper - Fresh, Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (247, 3354, 'Rice - Long Grain');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (248, 6913, 'Rice - Sushi');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (249, 7586, 'Wine - Red, Cabernet Merlot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (250, 8103, 'Tea - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (251, 446, 'Juice - Apple Cider');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (252, 4778, 'Juice - Clam, 46 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (253, 8176, 'Coconut - Shredded, Sweet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (254, 150, 'Lid Coffee Cup 8oz Blk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (255, 8927, 'Corn Shoots');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (256, 329, 'Yogurt - Peach, 175 Gr');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (257, 552, 'Potatoes - Pei 10 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (258, 6876, 'Appetiser - Bought');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (259, 4494, 'Cup - Paper 10oz 92959');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (260, 9336, 'Vinegar - Raspberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (261, 4879, 'Spinach - Baby');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (262, 9322, 'Snapple Lemon Tea');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (263, 2403, 'Pail For Lid 1537');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (264, 1627, 'Beef - Tenderloin Tails');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (265, 9320, 'Chicken - White Meat With Tender');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (266, 1626, 'Beef - Short Ribs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (267, 9167, 'Sauce - Balsamic Viniagrette');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (268, 6408, 'Sesame Seed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (269, 9593, 'Butter - Unsalted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (270, 2128, '7up Diet, 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (271, 8433, 'Syrup - Monin, Amaretta');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (272, 7823, 'Country Roll');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (273, 4092, 'Milk - Homo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (274, 8812, 'Beef - Ground Lean Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (275, 1793, 'Beer - Labatt Blue');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (276, 4570, 'Pastry - Lemon Danish - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (277, 1063, 'Tea - Herbal - 6 Asst');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (278, 2250, 'Wine - Chianti Classico Riserva');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (279, 4235, 'Juice - Orange');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (280, 540, 'Container - Foam Dixie 12 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (281, 1462, 'Icecream - Dstk Strw Chseck');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (282, 9150, 'Coffee - French Vanilla Frothy');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (283, 1936, 'Barramundi');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (284, 5315, 'Chips Potato All Dressed - 43g');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (285, 9120, 'Appetizer - Veg Assortment');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (286, 7708, 'Nantucket - Kiwi Berry Cktl.');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (287, 5372, 'Mushroom - Shitake, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (288, 314, 'Muffin Batt - Carrot Spice');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (289, 5829, 'Bacardi Raspberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (290, 950, 'Wine - Zinfandel Rosenblum');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (291, 8153, 'Salmon - Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (292, 5201, 'Nut - Chestnuts, Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (293, 4628, 'Basil - Seedlings Cookstown');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (294, 3199, 'Soup - Campbells, Lentil');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (295, 9848, 'Juice - Lemon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (296, 9698, 'Soup - Campbells Bean Medley');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (297, 4857, 'Cake Circle, Foil, Scallop');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (298, 5690, 'Appetizer - Crab And Brie');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (299, 4314, 'Ecolab Crystal Fusion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (300, 7753, 'Pasta - Lasagna Noodle, Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (301, 1513, 'Beef - Tenderloin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (302, 323, 'Beef - Top Butt Aaa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (303, 1394, 'Pastry - Choclate Baked');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (304, 575, 'Fish - Halibut, Cold Smoked');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (305, 7125, 'Bread - Italian Sesame Poly');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (306, 2790, 'Ecolab - Hand Soap Form Antibac');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (307, 730, 'Pork - Loin, Boneless');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (308, 6589, 'Cheese - Brie, Cups 125g');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (309, 9551, 'Steamers White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (310, 2716, 'Milk - 1%');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (311, 6694, 'Graham Cracker Mix');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (312, 3668, 'Appetizer - Tarragon Chicken');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (313, 5913, 'Kahlua');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (314, 7692, 'Corn - Cream, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (315, 6504, 'Nantucket - Pomegranate Pear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (316, 901, 'Pasta - Fusili Tri - Coloured');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (317, 2523, 'Cheese - Shred Cheddar / Mozza');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (318, 7698, 'Wine - Carmenere Casillero Del');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (319, 7835, 'Seabream Whole Farmed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (320, 8885, 'Wine - Chenin Blanc K.w.v.');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (321, 8517, 'Clams - Bay');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (322, 1577, 'Ecolab - Lime - A - Way 4/4 L');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (323, 627, 'Maple Syrup');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (324, 2453, 'Tomato - Peeled Italian Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (325, 2034, 'Mop Head - Cotton, 24 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (326, 4649, 'Dasheen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (327, 1204, 'Mustard - Pommery');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (328, 8043, 'Vinegar - Balsamic, White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (329, 4256, 'Vermouth - Sweet, Cinzano');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (330, 3770, 'Pastry - Chocolate Chip Muffin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (331, 6541, 'Noodles - Cellophane, Thin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (332, 8504, 'Vinegar - Red Wine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (333, 2889, 'Sauce - Demi Glace');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (334, 4915, 'Pork - Ham, Virginia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (335, 5397, 'Sprouts - Pea');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (336, 3607, 'Cup - 8oz Coffee Perforated');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (337, 131, 'Cheese - Montery Jack');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (338, 1108, 'Cookies Cereal Nut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (339, 1617, 'Vacuum Bags 12x16');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (340, 1660, 'Napkin White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (341, 5394, 'Nantucket Cranberry Juice');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (342, 5002, 'Cheese - Woolwich Goat, Log');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (343, 8522, 'Apron');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (344, 2296, 'Soup - Verve - Chipotle Chicken');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (345, 3576, 'Soup - French Onion, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (346, 3364, 'Juice - Cranberry, 341 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (347, 4663, 'Beef - Cow Feet Split');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (348, 985, 'Soup - Campbells Broccoli');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (349, 6623, 'Sterno - Chafing Dish Fuel');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (350, 7999, 'Pail For Lid 1537');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (351, 5427, 'Shrimp - Black Tiger 6 - 8');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (352, 3535, 'Pail - 15l White, With Handle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (353, 2661, 'Soup Knorr Chili With Beans');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (354, 9821, 'Wild Boar - Tenderloin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (355, 9580, 'Nut - Chestnuts, Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (356, 4198, 'Rye Special Old');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (357, 7362, 'Cup - 6oz, Foam');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (358, 8695, 'Gatorade - Xfactor Berry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (359, 7436, 'Soup - Base Broth Beef');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (360, 4760, 'Wine - Red, Gamay Noir');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (361, 8805, 'Scotch - Queen Anne');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (362, 6323, 'Fireball Whisky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (363, 8654, 'Fond - Chocolate');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (364, 2720, 'Squid - U - 10 Thailand');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (365, 2820, 'Yogurt - Blueberry, 175 Gr');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (366, 8470, 'Plums - Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (367, 75, 'Beer - Original Organic Lager');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (368, 9860, 'Food Colouring - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (369, 4498, 'Bok Choy - Baby');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (370, 797, 'Amarula Cream');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (371, 7813, 'Canada Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (372, 269, 'Tendrils - Baby Pea, Organic');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (373, 5372, 'Oranges - Navel, 72');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (374, 4009, 'Lid - High Heat, Super Clear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (375, 2763, 'Bread - Bagels, Plain');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (376, 7675, 'Beans - Kidney White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (377, 7198, 'Muffin Hinge - 211n');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (378, 5526, 'Dried Cranberries');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (379, 9169, 'Wine - Red, Pelee Island Merlot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (380, 4944, 'Artichoke - Hearts, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (381, 6738, 'Tomatoes - Diced, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (382, 7295, 'Wine - Red, Marechal Foch');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (383, 2703, 'Beets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (384, 8036, 'Wine - Alicanca Vinho Verde');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (385, 804, 'Muffin Hinge - 211n');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (386, 7018, 'Lamb - Bones');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (387, 137, 'Tea - Earl Grey');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (388, 7553, 'Spice - Montreal Steak Spice');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (389, 385, 'Plums - Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (390, 7373, 'Beef - Tender Tips');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (391, 8698, 'Bread - Calabrese Baguette');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (392, 4304, 'Radish - Black, Winter, Organic');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (393, 3994, 'Chinese Lemon Pork');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (394, 9874, 'Foam Espresso Cup Plain White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (395, 42, 'Puree - Mocha');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (396, 7161, 'Shrimp - Prawn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (397, 9211, 'Table Cloth 53x69 White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (398, 1107, 'Sausage - Blood Pudding');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (399, 9164, 'Alize Red Passion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (400, 1766, 'Pate - Peppercorn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (401, 4092, 'Garlic Powder');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (402, 4596, 'Sprouts - Brussel');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (403, 2415, 'Longos - Chicken Caeser Salad');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (404, 3522, 'Parsley Italian - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (405, 1092, 'Mikes Hard Lemonade');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (406, 4452, 'Steel Wool');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (407, 8430, 'Bread - Raisin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (408, 263, 'Ecolab - Lime - A - Way 4/4 L');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (409, 5614, 'Caviar - Salmon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (410, 9434, 'Juice - Apple Cider');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (411, 1313, 'Cleaner - Pine Sol');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (412, 2928, 'Bread - Crumbs, Bulk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (413, 2533, 'Hickory Smoke, Liquid');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (414, 3849, 'Plate - Foam, Bread And Butter');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (415, 2579, 'Melon - Watermelon Yellow');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (416, 2879, 'Longos - Chicken Curried');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (417, 4294, 'Mushroom - Shitake, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (418, 5971, 'Extract - Vanilla,artificial');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (419, 9774, 'Milk - Skim');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (420, 6097, 'Wine - Lamancha Do Crianza');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (421, 440, 'Beef Cheek Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (422, 9943, 'Sauce - Thousand Island');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (423, 9038, 'Wine - Port Late Bottled Vintage');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (424, 3834, 'Transfer Sheets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (425, 8607, 'Zucchini - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (426, 6724, 'Oven Mitts 17 Inch');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (427, 8176, 'Pork - Ham Hocks - Smoked');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (428, 452, 'Vinegar - Cider');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (429, 3148, 'Wine - Pinot Grigio Collavini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (430, 1690, 'Creme De Menth - White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (431, 754, 'Split Peas - Yellow, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (432, 5189, 'Pastry - Mini French Pastries');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (433, 1872, 'Soup - Campbells, Spinach Crm');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (434, 8951, 'Dr. Pepper - 355ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (435, 13, 'Grenadine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (436, 4269, 'Cocoa Feuilletine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (437, 9074, 'Brandy Apricot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (438, 3020, 'Chives - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (439, 4094, 'Beef - Tenderloin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (440, 4504, 'Tea - Orange Pekoe');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (441, 5220, 'Asparagus - Mexican');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (442, 6492, 'Appetizer - Chicken Satay');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (443, 3179, 'Wine - White, Concha Y Toro');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (444, 4399, 'Tart - Lemon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (445, 187, 'Wine - Peller Estates Late');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (446, 5764, 'Rice - Brown');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (447, 1477, 'Pastry - Lemon Danish - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (448, 2403, 'Campari');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (449, 6278, 'Chocolate - Chips Compound');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (450, 79, 'Lemonade - Pineapple Passion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (451, 5021, 'Bandage - Flexible Neon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (452, 9933, 'Water, Tap');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (453, 9751, 'Fruit Mix - Light');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (454, 3161, 'Noodles - Steamed Chow Mein');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (455, 3134, 'Juice - Mango');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (456, 130, 'Soup - Cream Of Broccoli, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (457, 2044, 'Soup - Campbells Tomato Ravioli');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (458, 3164, 'Sprite - 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (459, 230, 'Tomatoes - Diced, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (460, 9499, 'Olive - Spread Tapenade');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (461, 6431, 'Cheese - Mozzarella, Buffalo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (462, 1332, 'Juice - Pineapple, 48 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (463, 6443, 'Mushroom - White Button');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (464, 552, 'Muffin Mix - Carrot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (465, 3179, 'Cabbage Roll');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (466, 1465, 'Wasabi Paste');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (467, 3948, 'Compound - Raspberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (468, 4665, 'Pork - Backfat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (469, 641, 'Beets - Candy Cane, Organic');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (470, 5791, 'Vector Energy Bar');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (471, 390, 'Steampan - Lid For Half Size');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (472, 4236, 'Lid - High Heat, Super Clear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (473, 4460, 'Curry Powder Madras');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (474, 4482, 'Veal - Sweetbread');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (475, 4478, 'Sun - Dried Tomatoes');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (476, 7024, 'Appetizer - Smoked Salmon / Dill');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (477, 9496, 'Duck - Legs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (478, 1423, 'Apples - Spartan');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (479, 3544, 'Capon - Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (480, 4198, 'Veal - Round, Eye Of');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (481, 1975, 'Tart - Butter Plain Squares');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (482, 4716, 'Oil - Safflower');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (483, 4254, 'Pork - Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (484, 4195, 'Cabbage - Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (485, 3742, 'Kahlua');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (486, 5891, 'Chips Potato Salt Vinegar 43g');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (487, 8042, 'Tomato - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (488, 9086, 'Bandage - Fexible 1x3');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (489, 3228, 'Wine - Rosso Del Veronese Igt');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (490, 4303, 'Ice Cream Bar - Hageen Daz To');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (491, 8685, 'Doilies - 8, Paper');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (492, 9321, 'Glycerine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (493, 128, 'Ginger - Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (494, 2734, 'Beef - Shank');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (495, 2010, 'Skirt - 29 Foot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (496, 1199, 'Cookie Dough - Chunky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (497, 9687, 'Crab - Blue, Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (498, 9886, 'Food Colouring - Blue');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (499, 1631, 'Rice - Jasmine Sented');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (500, 1414, 'Cookie Dough - Chocolate Chip');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (501, 6988, 'Chocolate Eclairs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (502, 1934, 'Cake - Box Window 10x10x2.5');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (503, 253, 'Oil - Coconut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (504, 6378, 'Juice - Happy Planet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (505, 3679, 'Bread - Burger');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (506, 9621, 'Pear - Asian');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (507, 6422, 'Pork - Side Ribs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (508, 2974, 'Dry Ice');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (509, 3643, 'Lid - 0090 Clear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (510, 8312, 'Beef - Ox Tongue, Pickled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (511, 9658, 'Nori Sea Weed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (512, 7443, 'Pepper - White, Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (513, 1931, 'Wine - Remy Pannier Rose');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (514, 3990, 'Appetizer - Veg Assortment');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (515, 1508, 'Berry Brulee');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (516, 8701, 'Lemon Pepper');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (517, 5088, 'Kiwi');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (518, 5954, 'Soy Protein');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (519, 8010, 'Mackerel Whole Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (520, 8223, 'Pear - Prickly');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (521, 4596, 'Figs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (522, 7993, 'Easy Off Oven Cleaner');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (523, 4000, 'Sprouts - Peppercress');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (524, 7015, 'Gatorade - Orange');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (525, 2033, 'Tarragon - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (526, 5650, 'Tuna - Yellowfin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (527, 6672, 'Pork - Back, Long Cut, Boneless');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (528, 6705, 'Bread - Hot Dog Buns');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (529, 7825, 'Curry Powder');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (530, 9815, 'Tart Shells - Sweet, 2');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (531, 1944, 'Pastry - Plain Baked Croissant');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (532, 4757, 'Chips - Assorted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (533, 6827, 'Trout - Rainbow, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (534, 1330, 'Bar Bran Honey Nut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (535, 1376, 'Kiwano');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (536, 1377, 'Turnip - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (537, 1917, 'Wine - Periguita Fonseca');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (538, 5910, 'Bread Base - Gold Formel');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (539, 2372, 'Wine - Remy Pannier Rose');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (540, 8209, 'Cheese - Brie,danish');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (541, 1195, 'Wine - Two Oceans Sauvignon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (542, 5896, 'Laundry - Bag Cloth');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (543, 8298, 'Beer - Camerons Auburn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (544, 6393, 'Ecolab - Mikroklene 4/4 L');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (545, 8611, 'Water - Mineral, Carbonated');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (546, 7868, 'Chevere Logs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (547, 6537, 'Hipnotiq Liquor');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (548, 5313, 'Coffee Cup 8oz 5338cd');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (549, 1674, 'Pastry - Apple Muffins - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (550, 3511, 'Veal - Brisket, Provimi,bnls');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (551, 3888, 'Currants');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (552, 6558, 'Bagel - 12 Grain Preslice');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (553, 8295, 'Pasta - Gnocchi, Potato');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (554, 8611, 'Chocolate Liqueur - Godet White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (555, 9348, 'Wine - Jackson Triggs Okonagan');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (556, 7454, 'Pear - Packum');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (557, 9163, 'Cookies - Amaretto');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (558, 189, 'Soy Protein');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (559, 7347, 'Soup Bowl Clear 8oz92008');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (560, 3117, 'Cabbage - Nappa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (561, 9290, 'Wine - Ruffino Chianti Classico');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (562, 8186, 'Champagne - Brights, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (563, 4495, 'Tumeric');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (564, 7485, 'Beer - Creemore');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (565, 861, 'Cookies Oatmeal Raisin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (566, 3493, 'Container - Clear 32 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (567, 5600, 'Truffle Shells - Semi - Sweet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (568, 3880, 'Chicken - Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (569, 7531, 'Wine - Chablis J Moreau Et Fils');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (570, 6795, 'Ginger - Crystalized');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (571, 7573, 'Yoplait Drink');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (572, 2190, 'Nestea - Ice Tea, Diet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (573, 3205, 'Cauliflower');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (574, 487, 'Ginger - Pickled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (575, 8501, 'Bread - Italian Corn Meal Poly');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (576, 5461, 'Beef - Short Loin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (577, 4640, 'Compound - Passion Fruit');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (578, 5798, 'Ostrich - Fan Fillet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (579, 7489, 'Spice - Pepper Portions');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (580, 5822, 'Foil - 4oz Custard Cup');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (581, 5635, 'Red Snapper - Fillet, Skin On');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (582, 3608, 'Juice - Propel Sport');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (583, 433, 'Beef - Roasted, Cooked');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (584, 3974, 'Bag - Regular Kraft 20 Lb');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (585, 2230, 'Sea Bass - Fillets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (586, 5232, 'Soup - Canadian Pea, Dry Mix');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (587, 1395, 'Ice Cream Bar - Oreo Cone');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (588, 4938, 'Sauce - White, Mix');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (589, 7263, 'Puree - Kiwi');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (590, 1353, 'Wine - Taylors Reserve');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (591, 1396, 'Mushroom - Chanterelle Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (592, 9600, 'Goat - Leg');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (593, 6108, 'Broom And Broom Rack White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (594, 7652, 'Lobster - Live');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (595, 3742, 'Wine - Rhine Riesling Wolf Blass');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (596, 102, 'Wine - Hardys Bankside Shiraz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (597, 1391, 'Water - Mineral, Natural');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (598, 4961, 'Contreau');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (599, 6652, 'Pasta - Tortellini, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (600, 1505, 'Broom And Brush Rack Black');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (601, 7198, 'Longos - Lasagna Beef');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (602, 9262, 'Crab - Meat Combo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (603, 6831, 'Cookie Dough - Oatmeal Rasin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (604, 5894, 'Pears - Bartlett');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (605, 4215, 'Flower - Daisies');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (606, 8274, 'Chicken - Ground');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (607, 834, 'Juice Peach Nectar');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (608, 4751, 'Lamb - Sausage Casings');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (609, 6328, 'Ezy Change Mophandle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (610, 5894, 'Pastry - Raisin Muffin - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (611, 8100, 'Lettuce - Iceberg');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (612, 5382, 'Energy Drink - Franks Original');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (613, 4032, 'Kiwi Gold Zespri');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (614, 3391, 'Sterno - Chafing Dish Fuel');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (615, 4078, 'Nut - Chestnuts, Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (616, 4457, 'Juice - Cranberry 284ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (617, 6160, 'Beer - Steamwhistle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (618, 3535, 'Puree - Mango');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (619, 7754, 'Pasta - Tortellini, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (620, 6532, 'Soup - Campbells, Chix Gumbo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (621, 2063, 'Loaf Pan - 2 Lb, Foil');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (622, 6917, 'Cheese - Camembert');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (623, 9238, 'Yogurt - Plain');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (624, 3126, 'Watercress');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (625, 1268, 'Garbage Bags - Clear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (626, 2319, 'Cherries - Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (627, 5348, 'Pork Casing');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (628, 6222, 'Vodka - Moskovskaya');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (629, 5747, 'Muffin - Mix - Bran And Maple 15l');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (630, 559, 'Nescafe - Frothy French Vanilla');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (631, 2259, 'Apple - Delicious, Golden');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (632, 3926, 'Beets - Golden');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (633, 6699, 'Pork - Tenderloin, Frozen');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (634, 4732, 'Amaretto');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (635, 600, 'Carbonated Water - Orange');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (636, 4623, 'Wine - Masi Valpolocell');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (637, 8824, 'Bread - Multigrain Oval');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (638, 8436, 'Sherry - Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (639, 5738, 'Beer - Maudite');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (640, 2840, 'Bowl 12 Oz - Showcase 92012');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (641, 4842, 'Thyme - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (642, 3045, 'Pastry - Cherry Danish - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (643, 1436, 'Ostrich - Prime Cut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (644, 9974, 'Plasticspoonblack');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (645, 8497, 'Ocean Spray - Ruby Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (646, 8023, 'Beef - Prime Rib Aaa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (647, 3233, 'Latex Rubber Gloves Size 9');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (648, 3061, 'Pie Filling - Pumpkin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (649, 7015, 'Tea - Earl Grey');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (650, 7307, 'Nestea - Ice Tea, Diet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (651, 5935, 'Pepper - Chilli Seeds Mild');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (652, 7526, 'Cakes Assorted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (653, 3601, 'Kiwi Gold Zespri');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (654, 3256, 'Puree - Kiwi');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (655, 9202, 'Breadfruit');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (656, 6744, 'Instant Coffee');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (657, 9843, 'Gherkin - Sour');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (658, 7479, 'Glass Clear 8 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (659, 6557, 'Bar Energy Chocchip');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (660, 9515, 'Nut - Pecan, Pieces');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (661, 9605, 'Halibut - Whole, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (662, 3969, 'Tomatoes - Plum, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (663, 6931, 'Wine - Red, Mosaic Zweigelt');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (664, 7951, 'Lentils - Red, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (665, 3135, 'Coffee - French Vanilla Frothy');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (666, 9570, 'Coke - Diet, 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (667, 2691, 'Pineapple - Golden');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (668, 4887, 'Squash - Guords');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (669, 3090, 'Sugar Thermometer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (670, 9946, 'Chicken - Leg, Boneless');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (671, 9263, 'Pastry - Choclate Baked');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (672, 2057, 'Broccoli - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (673, 3041, 'Oil - Canola');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (674, 3307, 'Pasta - Cheese / Spinach Bauletti');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (675, 8775, 'Pur Value');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (676, 4810, 'Chocolate - Semi Sweet, Calets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (677, 182, 'Roe - Lump Fish, Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (678, 768, 'Alize Gold Passion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (679, 6497, 'Sea Bass - Fillets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (680, 8631, 'Chips - Doritos');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (681, 4347, 'Carbonated Water - Strawberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (682, 3636, 'Pork - Ham, Virginia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (683, 9440, 'Wine - Masi Valpolocell');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (684, 9912, 'Lemonade - Strawberry, 591 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (685, 9018, 'Wine - Cousino Macul Antiguas');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (686, 3811, 'Wine - Tio Pepe Sherry Fino');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (687, 4709, 'Pepper - Jalapeno');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (688, 368, 'Celery');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (689, 783, 'Wine - Pinot Noir Latour');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (690, 5561, 'Wine - White, Riesling, Semi - Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (691, 3807, 'Honey - Lavender');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (692, 2955, 'Rabbit - Saddles');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (693, 2664, 'Oil - Coconut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (694, 4691, 'Egg Patty Fried');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (695, 9092, 'Pasta - Linguini, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (696, 7287, 'Amaretto');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (697, 11, 'Scallops - Live In Shell');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (698, 183, 'Wine - Rubyport');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (699, 2392, 'Pie Pecan');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (700, 8026, 'Marsala - Sperone, Fine, D.o.c.');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (701, 8366, 'Tea - Herbal - 6 Asst');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (702, 9472, 'Chocolate - Semi Sweet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (703, 982, 'Compound - Strawberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (704, 4434, 'Ginger - Pickled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (705, 3440, 'The Pop Shoppe - Cream Soda');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (706, 1949, 'Pastry - Apple Large');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (707, 5974, 'Juice - Lagoon Mango');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (708, 347, 'Pepper - Scotch Bonnet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (709, 7400, 'Relish');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (710, 3401, 'Sorrel - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (711, 2408, 'Shallots');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (712, 1785, 'Truffle Cups - Brown');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (713, 8425, 'Sauce - Hoisin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (714, 4716, 'Pepper - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (715, 5246, 'Fennel');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (716, 9343, 'Wine - White, Gewurtzraminer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (717, 2583, 'Rice Pilaf, Dry,package');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (718, 9510, 'Scallop - St. Jaques');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (719, 2098, 'Kumquat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (720, 7384, 'Nut - Hazelnut, Ground, Natural');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (721, 4786, 'Coconut - Shredded, Unsweet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (722, 4356, 'Juice - Lagoon Mango');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (723, 6748, 'Silicone Paper 16.5x24');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (724, 9754, 'Dill - Primerba, Paste');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (725, 859, 'Flower - Commercial Spider');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (726, 2847, 'Champagne - Brights, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (727, 1175, 'Bar - Granola Trail Mix Fruit Nut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (728, 6201, 'Vinegar - Cider');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (729, 2156, 'Cake - Miini Cheesecake Cherry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (730, 1638, 'Apples - Spartan');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (731, 4526, 'Flour - So Mix Cake White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (732, 2737, 'Pork - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (733, 4877, 'Shiratamako - Rice Flour');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (734, 4942, 'Kaffir Lime Leaves');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (735, 6034, 'Salmon Steak - Cohoe 8 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (736, 5002, 'Sprouts - Corn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (737, 7709, 'Wine - Cotes Du Rhone Parallele');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (738, 1371, 'Rice - Basmati');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (739, 2358, 'Orange Roughy 4/6 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (740, 2963, 'Eggplant Italian');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (741, 9589, 'Jerusalem Artichoke');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (742, 2338, 'Alize Gold Passion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (743, 1400, 'Sole - Dover, Whole, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (744, 675, 'Mushroom Morel Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (745, 2283, 'Sauce Bbq Smokey');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (746, 8944, 'Cherries - Maraschino,jar');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (747, 285, 'Creme De Menthe Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (748, 9952, 'Muffin Hinge Container 6');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (749, 1302, 'Sole - Iqf');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (750, 7760, 'Cherries - Maraschino,jar');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (751, 8433, 'Clementine');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (752, 7813, 'Pasta - Rotini, Colour, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (753, 6662, 'Wine - Zinfandel California 2002');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (754, 5008, 'Beef - Eye Of Round');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (755, 3825, 'Canadian Emmenthal');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (756, 6924, 'Veal - Inside');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (757, 9578, 'Pepper - White, Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (758, 2954, 'Guinea Fowl');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (759, 6721, 'Wakami Seaweed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (760, 5890, 'Beer - Moosehead');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (761, 4271, 'Beans - Kidney, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (762, 6542, 'Squash - Sunburst');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (763, 1425, 'Bread - Rolls, Rye');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (764, 9750, 'Magnotta Bel Paese Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (765, 3796, 'Tart - Pecan Butter Squares');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (766, 6633, 'Kumquat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (767, 577, 'Calypso - Pineapple Passion');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (768, 7465, 'Barramundi');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (769, 1364, 'Vinegar - Sherry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (770, 5295, 'Pie Filling - Apple');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (771, 9780, 'Duck - Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (772, 3102, 'Thyme - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (773, 7784, 'Bread - Hot Dog Buns');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (774, 8779, 'Salt - Table');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (775, 9875, 'Trout - Rainbow, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (776, 7515, 'Wine - Fontanafredda Barolo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (777, 7194, 'Longos - Assorted Sandwich');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (778, 7491, 'Cheese - Grana Padano');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (779, 2555, 'Pork - Chop, Frenched');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (780, 1928, 'Pate - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (781, 3501, 'Coffee Cup 12oz 5342cd');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (782, 6818, 'Bread - Roll, Canadian Dinner');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (783, 7951, 'Bar Mix - Lemon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (784, 5136, 'Avocado');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (785, 9299, 'Cinnamon Buns Sticky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (786, 9237, 'Paper Cocktail Umberlla 80 - 180');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (787, 6188, 'Pan Grease');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (788, 6478, 'Food Colouring - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (789, 7841, 'Appetizer - Southwestern');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (790, 5426, 'Wine - Pinot Grigio Collavini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (791, 7315, 'Beef - Top Sirloin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (792, 7156, 'Pie Shells 10');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (793, 9442, 'Walkers Special Old Whiskey');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (794, 3579, 'Radish - Black, Winter, Organic');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (795, 6061, 'Tomatoes - Diced, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (796, 5900, 'Muffin Chocolate Individual Wrap');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (797, 946, 'Bread - Sour Batard');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (798, 6910, 'Gatorade - Fruit Punch');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (799, 2818, 'Muffin Mix - Oatmeal');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (800, 2264, 'Appetizer - Veg Assortment');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (801, 8592, 'Veal - Shank, Pieces');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (802, 7102, 'Pickles - Gherkins');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (803, 1473, 'Bar Mix - Pina Colada, 355 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (804, 5418, 'Milk - Chocolate 500ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (805, 1883, 'Tortillas - Flour, 8');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (806, 8123, 'Soap - Hand Soap');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (807, 3205, 'Wine - Two Oceans Sauvignon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (808, 3126, 'Seaweed Green Sheets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (809, 8489, 'Marjoram - Dried, Rubbed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (810, 7369, 'Crab - Dungeness, Whole');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (811, 892, 'Oil - Shortening,liqud, Fry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (812, 3089, 'Cake - Miini Cheesecake Cherry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (813, 3820, 'Soup - French Onion, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (814, 2740, 'Wine - Wyndham Estate Bin 777');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (815, 3227, 'Cheese - Sheep Milk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (816, 8329, 'Muffin Carrot - Individual');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (817, 3709, 'Veal - Leg');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (818, 4904, 'Longos - Grilled Chicken With');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (819, 2249, 'Squid U5 - Thailand');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (820, 4474, 'Cheese - Augre Des Champs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (821, 2368, 'Calypso - Lemonade');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (822, 4602, 'Oregano - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (823, 6864, 'Chestnuts - Whole,canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (824, 5159, 'Calypso - Lemonade');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (825, 69, 'Soup - Campbells, Butternut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (826, 9830, 'Vinegar - Balsamic, White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (827, 2056, 'Lamb Rack Frenched Australian');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (828, 8109, 'Soup Campbells - Italian Wedding');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (829, 2049, 'Pork - Liver');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (830, 7805, 'Sugar - White Packet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (831, 64, 'Flour - Bread');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (832, 1640, 'Carbonated Water - Orange');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (833, 2931, 'Onions - Vidalia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (834, 6123, 'Pork - Loin, Center Cut');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (835, 8605, 'Lid Tray - 12in Dome');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (836, 212, 'Chocolate - Chips Compound');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (837, 6393, 'Tart Shells - Savory, 3');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (838, 4235, 'Cream - 18%');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (839, 2607, 'Bonito Flakes - Toku Katsuo');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (840, 1636, 'Gatorade - Orange');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (841, 5206, 'Mini - Vol Au Vents');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (842, 5922, 'Yogurt - Plain');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (843, 7961, 'Bread - Bistro White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (844, 2732, 'Beef - Ox Tongue, Pickled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (845, 3553, 'Spice - Greek 1 Step');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (846, 8204, 'Lid - 3oz Med Rec');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (847, 8745, 'Bread - Rolls, Corn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (848, 6990, 'Bagels Poppyseed');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (849, 6089, 'Muffin Mix - Chocolate Chip');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (850, 5583, 'Coconut - Creamed, Pure');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (851, 3637, 'Wine - Niagara,vqa Reisling');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (852, 6160, 'Contreau');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (853, 9707, 'Bacardi Limon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (854, 7070, 'Wine - Bouchard La Vignee Pinot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (855, 6404, 'Napkin - Beverge, White 2 - Ply');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (856, 8072, 'Egg Patty Fried');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (857, 2381, 'Raisin - Dark');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (858, 7366, 'Peach - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (859, 3829, 'Bagel - Plain');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (860, 7689, 'Beef - Ox Tongue');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (861, 8778, 'Seedlings - Clamshell');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (862, 2710, 'Fireball Whisky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (863, 9252, 'Ham - Procutinni');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (864, 8590, 'Yogurt - Peach, 175 Gr');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (865, 7006, 'Juice - Grape, White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (866, 4475, 'Mop Head - Cotton, 24 Oz');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (867, 1977, 'Sobe - Cranberry Grapefruit');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (868, 4535, 'Chicken - Whole Fryers');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (869, 6279, 'Sea Urchin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (870, 3105, 'Champagne - Brights, Dry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (871, 8011, 'Cheese - Camembert');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (872, 9026, 'Muffin - Bran Ind Wrpd');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (873, 3954, 'Lotus Leaves');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (874, 77, 'Stock - Beef, Brown');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (875, 3746, 'Longos - Chicken Cordon Bleu');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (876, 910, 'Sour Cream');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (877, 8699, 'Sauce - Mint');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (878, 2532, 'Pastry - Cherry Danish - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (879, 7688, 'Uniform Linen Charge');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (880, 8379, 'Trueblue - Blueberry Cranberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (881, 787, 'Wine - Red, Marechal Foch');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (882, 4314, 'Soup - Knorr, Ministrone');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (883, 8956, 'Cookies - Assorted');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (884, 2199, 'Worcestershire Sauce');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (885, 5843, 'Coffee - Colombian, Portioned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (886, 940, 'Scallops 60/80 Iqf');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (887, 4581, 'Lamb - Bones');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (888, 9660, 'Bread - Roll, Whole Wheat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (889, 6415, 'Food Colouring - Blue');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (890, 1824, 'Beer - Sleeman Fine Porter');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (891, 5966, 'Bread - Roll, Soft White Round');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (892, 892, 'Wine - Magnotta, Merlot Sr Vqa');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (893, 7079, 'Onions - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (894, 3529, 'Sole - Iqf');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (895, 1829, 'Rum - Coconut, Malibu');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (896, 385, 'Potatoes - Peeled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (897, 5354, 'Cheese - Cottage Cheese');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (898, 5707, 'Oil - Macadamia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (899, 1920, 'Butcher Twine 4r');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (900, 9658, 'Ecolab - Mikroklene 4/4 L');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (901, 2489, 'Bread - Sour Batard');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (902, 251, 'Pepper - Paprika, Spanish');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (903, 8526, 'Onions - Dried, Chopped');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (904, 7536, 'Yokaline');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (905, 9958, 'Beer - Sleemans Cream Ale');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (906, 6746, 'Dill Weed - Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (907, 1366, 'Wine - Maipo Valle Cabernet');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (908, 7785, 'Longos - Chicken Caeser Salad');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (909, 9833, 'Anisette - Mcguiness');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (910, 9809, 'Oil - Olive, Extra Virgin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (911, 3474, 'Pears - Bartlett');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (912, 5854, 'Buttons');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (913, 1579, 'Wine - Pinot Noir Mondavi Coastal');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (914, 5962, 'Gatorade - Lemon Lime');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (915, 3155, 'Black Currants');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (916, 7765, 'Ice Cream - Strawberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (917, 4813, 'Pear - Packum');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (918, 4728, 'Kellogs Raisan Bran Bars');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (919, 2266, 'Cheese - Comtomme');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (920, 2587, 'Soup - Cream Of Potato / Leek');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (921, 6226, 'Pepper - Chipotle, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (922, 9814, 'Bread Roll Foccacia');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (923, 7501, 'Cup - Translucent 7 Oz Clear');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (924, 8334, 'Squid - U - 10 Thailand');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (925, 945, 'Veal - Brisket, Provimi, Bone - In');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (926, 7132, 'Wiberg Cure');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (927, 8574, 'Cheese - Brie,danish');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (928, 7572, 'Fish - Halibut, Cold Smoked');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (929, 1164, 'Muffin Hinge Container 6');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (930, 3139, 'Coffee - Irish Cream');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (931, 7162, 'Cheese - Roquefort Pappillon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (932, 370, 'Chocolate - Chips Compound');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (933, 6822, 'Pineapple - Regular');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (934, 3752, 'Salt - Celery');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (935, 4856, 'Carbonated Water - Wildberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (936, 5154, 'Lamb - Leg, Boneless');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (937, 6196, 'Beans - Black Bean, Canned');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (938, 3157, 'Cheese - Pied De Vents');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (939, 5247, 'Onions - Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (940, 2192, 'Tart Shells - Sweet, 3');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (941, 5596, 'Salt - Celery');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (942, 5413, 'Pea - Snow');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (943, 876, 'Chips Potato All Dressed - 43g');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (944, 990, 'Rootbeer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (945, 890, 'Cookie Dough - Chunky');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (946, 243, 'Fork - Plastic');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (947, 456, 'Capon - Breast, Double, Wing On');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (948, 7852, 'Beef - Sushi Flat Iron Steak');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (949, 1569, 'Burger Veggie');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (950, 6446, 'Muffin Chocolate Individual Wrap');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (951, 6541, 'Milk - Buttermilk');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (952, 2067, 'Cheese - Cheddar With Claret');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (953, 2624, 'Corn - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (954, 6230, 'Nut - Hazelnut, Ground, Natural');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (955, 6359, 'Longos - Burritos');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (956, 5470, 'Lamb - Leg, Bone In');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (957, 5288, 'Lid Coffeecup 12oz D9542b');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (958, 5301, 'Nantucket - Orange Mango Cktl');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (959, 9227, 'Flour - Rye');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (960, 4232, 'Aromat Spice / Seasoning');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (961, 7447, 'Loquat');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (962, 9103, 'Beer - True North Lager');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (963, 3672, 'Wine - Red, Cabernet Merlot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (964, 2767, 'Lettuce - Curly Endive');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (965, 7428, 'Wine - Jackson Triggs Okonagan');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (966, 3183, 'Beef - Kobe Striploin');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (967, 8139, 'Chef Hat 25cm');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (968, 532, 'Wine - Two Oceans Sauvignon');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (969, 1601, 'Figs');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (970, 7793, 'Cheese - Pont Couvert');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (971, 7654, 'Energy Drink Bawls');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (972, 8427, 'Table Cloth 53x69 White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (973, 5025, 'Pail - 4l White, With Handle');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (974, 6851, 'Wine - Alsace Gewurztraminer');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (975, 26, 'Mushroom - Enoki, Fresh');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (976, 6244, 'Table Cloth 53x69 White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (977, 9881, 'Radish - Pickled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (978, 6644, 'Cheese - Woolwich Goat, Log');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (979, 3274, 'Milk 2% 500 Ml');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (980, 7787, 'Lychee');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (981, 968, 'Pastry - Cheese Baked Scones');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (982, 3885, 'Kahlua');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (983, 9077, 'Table Cloth 81x81 White');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (984, 3895, 'Plasticspoonblack');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (985, 617, 'Yogurt - Peach, 175 Gr');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (986, 8163, 'Coffee - Dark Roast');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (987, 1019, 'Cabbage - Green');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (988, 6768, 'Sauce - Hp');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (989, 4183, 'Sherbet - Raspberry');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (990, 8833, 'Mints - Striped Red');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (991, 5767, 'Potatoes - Peeled');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (992, 7528, 'Brandy Apricot');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (993, 3165, 'Cucumber - English');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (994, 1979, 'Cake Slab');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (995, 7264, 'Sprouts - Corn');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (996, 5865, 'Cheese - Oka');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (997, 7278, 'Ecolab - Hobart Washarm End Cap');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (998, 1166, 'Pie Filling - Apple');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (999, 1796, 'Pork Loin Cutlets');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1000, 2395, 'Bag - Bread, White, Plain');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1001, 2262, 'Pastry - Carrot Muffin - Mini');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1002, 4083, 'Muffin Hinge Container 6');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1003, 1992, 'Chips - Miss Vickies');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1004, 5102, 'V8 - Tropical Blend');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1005, 7537, 'Sugar - Icing');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1006, 100213, 'Prueba');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1007, 100213, 'Prueba123');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1008, 1548, 'Hola');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1009, 78945411487984, 'Paleta-Dracula');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1010, 123, 'Dulce');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1011, 1, 'Gominola');
INSERT INTO inventario.inv (id, cantidad, nombre) VALUES (1012, 13, 'stefanny');